name: ROS 2 CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  jazzy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy
      - name: Install AprilTag message package
        run: sudo apt-get update && sudo apt-get install -y ros-jazzy-apriltag-msgs
      - uses: ros-tooling/action-ros-ci@v0.4
        env:
          LD_LIBRARY_PATH: /opt/ros/jazzy/lib/x86_64-linux-gnu:/opt/ros/jazzy/lib
        with:
          package-name: demo2_apriltag_docking
          target-ros2-distro: jazzy
          colcon-defaults: |
            {
              "build": {
                "symlink-install": true
              },
              "test": {
                "event-handlers": ["console_direct+"]
              }
            }
